;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        evilnc-comment-or-uncomment-lines
        orgtbl-hijacker-command-101
        orgtbl-self-insert-command
        sgml-slash
        yas-expand
        zencoding-expand-line
        ))

(setq mc/cmds-to-run-once
      '(
        kill-region
        ))
